### PR TITLE
Unicorn doesn't track item revisions

### PR DESCRIPTION
**Pull request by lordstyx**
Unicorn doesn't track revisions, so we need to add those ourselves wen an item is created or updated to make sure smart publish works.

### CODE REVIEW

**Review by WimVergouwe — APPROVED** [review]

**Review by StijnPlanckaert — COMMENTED** [review]
Doesn't sitecore also fill in the updated & updatedby fields on creation?

**Comment by WimVergouwe** [comment]
@StijnPlanckaert we don't use the Sitecore APIs, so that's not really relevant right?

**Comment by StijnPlanckaert** [comment]
@WimVergouwe don't we want to make sure that items are created in the db just the same as sitecore would create them using their api?

**Comment by WimVergouwe** [comment]
@StijnPlanckaert that's indeed why we need to set these statistics fields when using the bulkloader.

**Comment by StijnPlanckaert** [comment]
@WimVergouwe but the updated and updatedby statistics fields will only be set on update now (postProcessor: x => x.DependsOnUpdate = true), while sitecore api will also fill in those fields on creation.

**Comment by WimVergouwe** [comment]
@StijnPlanckaert ok, now I'm with you ;) Indeed that should be: x => x.DependsOnCreate = x.DependsOnUpdate = true
@lordstyx can you update please.

**Comment by lordstyx** [comment]
@WimVergouwe @StijnPlanckaert Done.

**Review by StijnPlanckaert — APPROVED** [review]

**Pull request merged**
